# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0002_auto_20160521_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runway',
            name='runway_identification',
            field=models.CharField(max_length=7),
        ),
    ]
