# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 23:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(blank=True, max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('upper_desc', models.CharField(max_length=16)),
                ('upper_val', models.IntegerField()),
                ('upper_uom', models.CharField(blank=True, max_length=16)),
                ('upper_code', models.CharField(blank=True, max_length=16)),
                ('lower_desc', models.CharField(max_length=16)),
                ('lower_val', models.IntegerField()),
                ('lower_uom', models.CharField(blank=True, max_length=16)),
                ('lower_code', models.CharField(blank=True, max_length=16)),
                ('type_code', models.CharField(max_length=16)),
                ('local_type', models.CharField(max_length=16)),
                ('airspace_class', models.CharField(max_length=16)),
                ('mil_code', models.CharField(max_length=16)),
                ('comm_name', models.CharField(blank=True, max_length=128)),
                ('level', models.CharField(max_length=16)),
                ('sector', models.CharField(blank=True, max_length=64)),
                ('onshore', models.IntegerField()),
                ('exclusion', models.IntegerField()),
                ('wkhr_code', models.CharField(max_length=16)),
                ('wkhr_remark', models.CharField(blank=True, max_length=128)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
