# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-12 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftregistration',
            name='mode_s_code',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='aircraftregistration',
            name='mode_s_code_hex',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
