# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-01-09 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_auto_20200312_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftmanufacturercode',
            name='aircraft_type',
            field=models.CharField(choices=[(1, 'Glider'), (2, 'Balloon'), (3, 'Blimp/Dirigible'), (4, 'Fixed wing single engine'), (5, 'Fixed wing multi engine'), (6, 'Rotorcraft'), (7, 'Weight-shift-control'), (8, 'Powered Parachute'), (9, 'Gyroplane')], max_length=1),
        ),
        migrations.AlterField(
            model_name='aircraftmanufacturercode',
            name='builder_certification_code',
            field=models.CharField(choices=[(0, 'Type Certificated'), (1, 'Not Type Certificated'), (2, 'Light Sport')], max_length=1),
        ),
        migrations.AlterField(
            model_name='aircraftmanufacturercode',
            name='category',
            field=models.CharField(choices=[(1, 'Land'), (2, 'Sea'), (3, 'Amphibian')], max_length=1),
        ),
        migrations.AlterField(
            model_name='aircraftmanufacturercode',
            name='engine_type',
            field=models.CharField(choices=[(0, 'None'), (1, 'Reciprocating'), (2, 'Turbo-prop'), (3, 'Turbo-shaft'), (4, 'Turbo-jet'), (5, 'Turbo-fan'), (6, 'Ramjet'), (7, '2 Cycle'), (8, '4 Cycle'), (9, 'Unknown')], max_length=1),
        ),
        migrations.AlterField(
            model_name='aircraftregistration',
            name='aircraft_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Glider'), (2, 'Balloon'), (3, 'Blimp/Dirigible'), (4, 'Fixed wing single engine'), (5, 'Fixed wing multi engine'), (6, 'Rotorcraft'), (7, 'Weight-shift-control'), (8, 'Powered Parachute'), (9, 'Gyroplane')], null=True),
        ),
        migrations.AlterField(
            model_name='aircraftregistration',
            name='airworthiness_classification_code',
            field=models.CharField(blank=True, choices=[(1, 'Standard'), (2, 'Limited'), (3, 'Restricted'), (4, 'Experimental'), (5, 'Provisional'), (6, 'Multiple'), (7, 'Primary'), (8, 'Special Flight Permit'), (9, 'Light Sport')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='aircraftregistration',
            name='engine_type',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Reciprocating'), (2, 'Turbo-prop'), (3, 'Turbo-shaft'), (4, 'Turbo-jet'), (5, 'Turbo-fan'), (6, 'Ramjet'), (7, '2 Cycle'), (8, '4 Cycle'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='aircraftregistration',
            name='geocode_type',
            field=models.CharField(blank=True, choices=[('zi', 'Zip Code')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='aircraftregistration',
            name='region',
            field=models.CharField(blank=True, choices=[(1, 'Eastern'), (2, 'Southwestern'), (3, 'Central'), (4, 'Western-Pacific'), (5, 'Alaskan'), (7, 'Southern'), (8, 'European'), ('C', 'Great Lakes'), ('E', 'New England'), ('S', 'Northwest Mountain')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='aircraftregistration',
            name='status_code',
            field=models.CharField(blank=True, choices=[('A', 'The Triennial Aircraft Registration form was mailed and has not been returned by the Post Office'), ('D', 'Expired Dealer'), ('E', 'The Certificate of Aircraft Registration was revoked by enforcement action'), ('M', 'Aircraft registered to the manufacturer under their Dealer Certificate'), ('N', 'Non-citizen Corporations which have not returned their flight hour reports'), ('R', 'Registration pending'), ('S', 'Second Triennial Aircraft Registration Form has been mailed'), ('T', 'Valid Registration from a Trainee'), ('V', 'Valid Registration'), ('X', 'Enforcement Letter'), ('Z', 'Permanent Reserved'), ('1', 'Triennial Aircraft Registration form was returned by the Post Office as undeliverable'), ('2', 'N-Number Assigned - but has not yet been registered'), ('3', 'N-Number assigned as a Non Type Certificated aircraft - but has not yet been registered'), ('4', 'N-Number assigned as import - but has not yet been registered'), ('5', 'Reserved N-Number'), ('6', 'Administratively canceled'), ('7', 'Sale reported'), ('8', 'A second attempt has been made at mailing a Triennial Aircraft Registration form to the owner with no response'), ('9', 'Certificate of Registration has been revoked'), ('10', 'N-Number assigned, has not been registered and is pending cancellation'), ('11', 'N-Number assigned as a Non Type Certificated (Amateur) but has not been registered that is pending cancellation'), ('12', 'N-Number assigned as import but has not been registered that is pending cancellation'), ('13', 'Registration Expired'), ('14', 'First Notice for Re-Registration/Renewal'), ('15', 'Second Notice for Re-Registration/Renewal'), ('16', 'Registration Expired - Pending Cancellation'), ('17', 'Sale Reported - Pending Cancellation'), ('18', 'Sale Reported - Canceled'), ('19', 'Registration Pending - Pending Cancellation'), ('20', 'Registration Pending - Canceled'), ('21', 'Revoked - Pending Cancellation'), ('22', 'Revoked - Canceled'), ('23', 'Expired Dealer (Pending Cancellation)'), ('24', 'Third Notice for Re-Registration/Renewal')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='aircraftregistration',
            name='type_registrant',
            field=models.IntegerField(blank=True, choices=[(1, 'Individual'), (2, 'Partnership'), (3, 'Corporation'), (4, 'Co-Owned'), (5, 'Government'), (8, 'Non-Citizen Corporation'), (9, 'Non-Citizen Co-Owned')], null=True),
        ),
    ]
