# Generated by Django 3.2.15 on 2023-03-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0004_auto_20220807_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineManufacturerAndModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=5)),
                ('manufacturer', models.CharField(max_length=16)),
                ('model', models.CharField(max_length=16)),
                ('type', models.CharField(max_length=4)),
                ('horsepower', models.PositiveIntegerField(blank=True, null=True)),
                ('lbs_thrust', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='aircraftmanufacturercode',
            name='engine_type',
            field=models.CharField(choices=[(0, 'None'), (1, 'Reciprocating'), (2, 'Turbo-prop'), (3, 'Turbo-shaft'), (4, 'Turbo-jet'), (5, 'Turbo-fan'), (6, 'Ramjet'), (7, '2 Cycle'), (8, '4 Cycle'), (9, 'Unknown'), (10, 'Electric'), (11, 'Rotary')], max_length=2),
        ),
        migrations.AlterField(
            model_name='aircraftregistration',
            name='engine_type',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Reciprocating'), (2, 'Turbo-prop'), (3, 'Turbo-shaft'), (4, 'Turbo-jet'), (5, 'Turbo-fan'), (6, 'Ramjet'), (7, '2 Cycle'), (8, '4 Cycle'), (9, 'Unknown'), (10, 'Electric'), (11, 'Rotary')], null=True),
        ),
    ]
