# Generated by Django 4.2.2 on 2023-07-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0006_alter_aircraftregistration_aircraft_mfr_model_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftregistration',
            name='airworthiness_classification_code',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('1', 'Standard'), ('2', 'Limited'), ('3', 'Restricted'), ('4', 'Experimental'), ('5', 'Provisional'), ('6', 'Multiple'), ('7', 'Primary'), ('8', 'Special Flight Permit'), ('9', 'Light Sport')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='aircraftregistration',
            name='region',
            field=models.CharField(blank=True, choices=[('1', 'Eastern'), ('2', 'Southwestern'), ('3', 'Central'), ('4', 'Western-Pacific'), ('5', 'Alaskan'), ('7', 'Southern'), ('8', 'European'), ('C', 'Great Lakes'), ('E', 'New England'), ('S', 'Northwest Mountain')], max_length=1, null=True),
        ),
    ]
